### ISSUE TITLE
Custom Post Type: Category and Tag filtering options

### ISSUE THREAD

**Issue by purplecones** [torounit/advanced-posts-blocks#16]
Firstly, this plugin is super useful so thank you for that.

I do have one limitation in that it does not allow me to filter custom post types by categories/tags like you can with regular posts. Is this possible to add or does it introduce too much complexity? Is it possible for me to override it myself?

Thanks again

**Comment by torounit** [comment]
@purplecones 
Create a custom taxonomy for that post type. The taxonomy must have `show_in_rest` set to true.
